http 
{
    server {
        listen 80;
        server_name "example.com";
    }

    server {
        listen 8080;
        server_name "test.com";
    }

server 
{
	listen 8080;
	server_name example.net;
}


     server {

        listen       80;

        server_name  " example.com ";


  }


server {
listen 8080;
server_name example.net; # コメント
}
}

# serverブロックの外側のコメントと空白


# # server {

# # listen


# # 8081;

# # server_name "example.org"; # コメント


# # }

# # 末尾にコメントと空白