http 
{
server 
{
    listen 8080;
    server_name 127.0.0.1;
    error_page 404 /404.html;
    error_page 500 /500.html;
    location /index.html 
    {
        root /Users/yusukesato/Desktop/ytm_webserve;
        index index.html;
    }
}
}
