# http 
# {
#     server {
#         listen 80;
#         server_name "example.com";
#         error_page 404 /404.html;
#         error_page 500 /500.html;
#         location / {
#             root /var/www/html;
#             index index.html index.htm;
#             allow_methods GET POST;
#         }

#      }

#     server {
#         listen 8080;
#         server_name "test.com";
#         error_page 404 /404.html;
#         error_page 500 /500.html;
#     }

# server 
# {
# 	listen 8080;
# 	server_name example.net;
# }


#      server {

#         listen       80;

#         server_name  " example.com ";


#   }


# server {
# listen 8080;
# server_name example.net; # コメント
# }
# }

# serverブロックの外側のコメントと空白


# server {

# listen


# 8081;

# server_name "example.org"; # コメント


# }

# # 末尾にコメントと空白\

http 
{
	server 
	{
		listen 8080;
		server_name example.com;

		error_page 404 /404.html;

		location /images.html
		{
			root /var/www/html;
			index index.html index.htm;
			allow_methods GET POST;
		}
	}
}