http {
    server {
        listen 8081;
        listen 8082;
        server_name 127.0.0.1;
        root  /home/ktakamat/Desktop/tokyo/web_push;
        index index.html;
        client_max_body_size 10;
        location /htm {
            allow_methods GET POST;
            index index.htm;
            autoindex on;
        }
    }
    server {
        server_name 127.0.0.1;
        root  /home/ktakamat/Desktop/tokyo/web_push;
        index index.html;
        location /html {
            allow_methods GET POST;
            autoindex on;
        }
    }
    server {
        listen 8083;
        listen 8084;
        listen 8085;
        server_name 10.16.3.9;
        root  /home/ktakamat/Desktop/tokyo/web_push;
        location / {
            allow_methods GET POST;
            autoindex on;
        }
        location /uploads {
            allow_methods GET POST;
            autoindex on;
        }
    }
}

