server {
    listen 80;
    server_name localhost;
    client_max_body_size 100;

    # ドキュメントルート
    root /var/www/html;  # PHPファイルを置く場所
    index index.php index.html index.htm;

    location /old-page {
        return 301 http://localhost:75/new-page;
    }

    location /new-page {
        # 新しいページの処理
        root /var/www/html;
        index new-page.html;
    }

    # 通常のリクエスト処理
    location / {
        try_files $uri $uri/ =404;
    }

    # PHP-FPMの設定
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php-fpm:9000;  # php-fpmサービスのホスト名とポート（Docker内のサービス名とポート）
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_index index.php;
    }

    # ファイルアップロード用の設定
    location /upload.php {
        include fastcgi_params;
        fastcgi_pass php-fpm:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_index index.php;
    }

        location /delete.php {
        include fastcgi_params;
        fastcgi_pass php-fpm:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_index index.php;
    }

    # ファイルアップロード用の設定（アップロードされたファイルを保存する場所）
    location /uploads/ {
        root /var/www/html;  # アップロードしたファイルを保存する場所（ホストのディレクトリとコンテナ内のディレクトリをマウント）
        try_files $uri $uri/ =404;
    }
}
