http{

  server {
    #(default) listen 127.0.0.1:80;
    #listen 127.0.0.1;
    listen 80;
    #listen *:8000;

    server_name "";


    client_max_body_size 100k;
    #(default) client_max_body_size 1m;
  }

  server {


    client_max_body_size 100k;
    #(default) client_max_body_size 1m;
  }

}
